## Numpy Basics

In [2]:
import numpy as np

## Creating Numpy/nd Arrays

In [3]:
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
a2 = np.array([[1,2],[3,4]])
print(a2)
print(type(a2))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [5]:
a3 = np.zeros((2,3))
print(a3)
print(type(a3))

[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [6]:
a4 = np.ones((2,3))
print(a4)
print(type(a4))

[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>


In [7]:
a5 = np.identity(3)
print(a5)
print(type(a5))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>


In [8]:
a6 = np.arange(3,10,2)
print(a6)
print(type(a6))

[3 5 7 9]
<class 'numpy.ndarray'>


In [9]:
a7 = np.linspace(5,10,5)
print(a7)
print(type(a7))

[ 5.    6.25  7.5   8.75 10.  ]
<class 'numpy.ndarray'>


In [10]:
a8 = a4.copy()
print(a8)
print(type(a8))

[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>


## Some Important nd Array attributes

In [11]:
a1

array([1, 2, 3, 4, 5])

In [12]:
print(a1.shape)
print(a2.shape)

(5,)
(2, 2)


In [13]:
print(a1.ndim)
print(a2.ndim)

1
2


In [14]:
print(a1.size)
print(a2.size)

5
4


In [15]:
print(a1.itemsize)
print(a2.itemsize)

4
4


In [16]:
print(a1.dtype)
print(a2.dtype)

int32
int32


In [17]:
a1.astype('float')

array([1., 2., 3., 4., 5.])

## Numpy Array better than Python List

### Occupy Less Space

In [18]:
import sys
x = range(100)
print(sys.getsizeof(x[5])*len(x))

2800


In [19]:
y = np.arange(100)
print(y.itemsize*y.size)

400


### Faster and Convenience

In [20]:
import time
x = range(100000000)
y = range(100000000, 200000000)
s_time = time.time()
z = [x+y for (x,y) in zip(x,y)]
print(time.time() - s_time)

15.847554206848145


In [21]:
x = np.arange(100000000)
y = np.arange(100000000, 200000000)
s_time = time.time()
z = x+y
print(time.time() - s_time)

5.259063959121704


## Indexing, Slicing and Iteration

In [22]:
x = np.arange(12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
# Indexing
print(x[1])

[4 5 6 7]


In [24]:
# Slicing
print(x[:, 3])
print(x[1, 1:3])
print(x[1:, 2:])

[ 3  7 11]
[5 6]
[[ 6  7]
 [10 11]]


In [25]:
# Iteration
for i in x:
    print(i)

for i in np.nditer(x):
    print(i, end=" ")

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0 1 2 3 4 5 6 7 8 9 10 11 

## Numpy Operations

In [27]:
x = np.array([1,2,3,4,5])
y = np.array([5,6,7,8,9])

In [37]:
# Vector Addition
print("Vector Addition: ", x+y)
# Vector Subtraction
print("Vector Subtraction: ", x-y)
# Vector Multiplication
print("Vector Multiplication: ",x*y)
# Scalar Multiplication
print("Scalar Multiplication: ",x*2)

Vector Addition:  [ 6  8 10 12 14]
Vector Subtraction:  [-4 -4 -4 -4 -4]
Vector Multiplication:  [ 5 12 21 32 45]
Scalar Multiplication:  [ 2  4  6  8 10]


In [38]:
# Mathematical Operation are done on every item on array
print(x>4)

[False False False False  True]


In [40]:
# Matrix Multiplication
x = np.arange(6).reshape((3,2))
y = np.arange(6).reshape((2,3))
z= x.dot(y)
print(z)

[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]


In [43]:
# Min and Max in whole matrix
print(z.min())
print(z.max())

# Min and Max at specific direction/axis in matrix
print(z.min(axis= 0))
print(z.max(axis= 0))
print(z.min(axis = 1))
print(z.max(axis = 1))

3
33
[3 4 5]
[15 24 33]
[ 3  9 15]
[ 5 19 33]


In [46]:
# Sum, Mean, Standard Deviation etc of the nd Array
print(z.sum())
print(z.sum(axis=0))
print(z.mean())
print(z.std())
print(np.median(z))

126
[27 42 57]
14.0
9.510228411791404
14.0


## Reshaping nd Array

In [47]:
print(z)
print(z.ndim)

[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]
2


In [51]:
print(z.ravel())
print(z.ravel().ndim)

[ 3  4  5  9 14 19 15 24 33]
1


In [53]:
print(z)
print(z.transpose())

[[ 3  4  5]
 [ 9 14 19]
 [15 24 33]]
[[ 3  9 15]
 [ 4 14 24]
 [ 5 19 33]]


In [56]:
x = np.arange(10).reshape((2,5))
y = np.arange(11,21).reshape((2,5))
print(np.hstack((x,y)))
print(np.vstack((x,y)))

[[ 0  1  2  3  4 11 12 13 14 15]
 [ 5  6  7  8  9 16 17 18 19 20]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [11 12 13 14 15]
 [16 17 18 19 20]]
